---
- name: Check if Zookeeper Service Running
  shell: "systemctl show -p SubState {{zookeeper_service_name}}"
  changed_when: false
  register: substate

# All zookeeper hosts iterate over the list of zookeeper hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match  the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Restart Zookeeper Serially
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups[zookeeper_ansible_group] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    - substate.stdout == 'SubState=running'

- name: Restart Zookeeper in Parallel
  include: restart.yml
  when: substate.stdout != 'SubState=running'
